version: 0.2 
phases: 
  install: 
    runtime-versions: 
        python: 3.7 
  build: 
    commands: 
      - export BUCKET=lambda-deployment-artifacts-rizwan 
      - aws cloudformation package --template-file SAM_Template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yml 
artifacts: 
  type: zip 
  files: 
    - SAM_Template.yaml 
    - outputtemplate.yml