AWSTemplateFormatVersion: '2010-09-09' 
Transform: AWS::Serverless-2016-10-31 
Description: Outputs Hello World text 
Resources: 
  TimeFunction: 
    Type: AWS::Serverless::Function 
    Properties: 
      Handler: lambda_function.lambda_handler 
      Runtime: python3.6 
      CodeUri: ./ 
      Events: 
        MyTimeApi: 
          Type: Api 
          Properties: 
            Path: / 
            Method: GET 